// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using Azure.Core;

namespace Microsoft.Bot.Connector.Client.Models
{
    /// <summary> Record for a token exchange request that is sent as part of an OAuthCard. </summary>
    [CodeGenModel(Formats = new[] { "json" }, Usage = new[] { "input", "output", "model" })]
    public partial class TokenResponse
    {
    }
}
